// ISO 3166-1 countries (top 30 by population + common English-speaking countries)
export const COUNTRIES = [
  { value: "US", label: "United States" },
  { value: "GB", label: "United Kingdom" },
  { value: "CA", label: "Canada" },
  { value: "AU", label: "Australia" },
  { value: "NZ", label: "New Zealand" },
  { value: "IN", label: "India" },
  { value: "CN", label: "China" },
  { value: "JP", label: "Japan" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "IT", label: "Italy" },
  { value: "ES", label: "Spain" },
  { value: "BR", label: "Brazil" },
  { value: "RU", label: "Russia" },
  { value: "MX", label: "Mexico" },
  { value: "ID", label: "Indonesia" },
  { value: "PK", label: "Pakistan" },
  { value: "NG", label: "Nigeria" },
  { value: "BD", label: "Bangladesh" },
  { value: "EG", label: "Egypt" },
  { value: "PH", label: "Philippines" },
  { value: "VN", label: "Vietnam" },
  { value: "TR", label: "Turkey" },
  { value: "IR", label: "Iran" },
  { value: "ZA", label: "South Africa" },
  { value: "KR", label: "South Korea" },
  { value: "MY", label: "Malaysia" },
  { value: "SG", label: "Singapore" },
  { value: "UA", label: "Ukraine" },
  { value: "SE", label: "Sweden" }
];

// ISO 639-1 languages (primary languages for the countries above + common business languages)
export const LANGUAGES = [
  { value: "en", label: "English" },
  { value: "zh", label: "Chinese" },
  { value: "hi", label: "Hindi" },
  { value: "es", label: "Spanish" },
  { value: "fr", label: "French" },
  { value: "ar", label: "Arabic" },
  { value: "bn", label: "Bengali" },
  { value: "ru", label: "Russian" },
  { value: "pt", label: "Portuguese" },
  { value: "id", label: "Indonesian" },
  { value: "ur", label: "Urdu" },
  { value: "ja", label: "Japanese" },
  { value: "de", label: "German" },
  { value: "pa", label: "Punjabi" },
  { value: "jv", label: "Javanese" },
  { value: "te", label: "Telugu" },
  { value: "vi", label: "Vietnamese" },
  { value: "ko", label: "Korean" },
  { value: "mr", label: "Marathi" },
  { value: "ta", label: "Tamil" },
  { value: "tr", label: "Turkish" },
  { value: "it", label: "Italian" },
  { value: "th", label: "Thai" },
  { value: "nl", label: "Dutch" },
  { value: "pl", label: "Polish" },
  { value: "sv", label: "Swedish" },
  { value: "da", label: "Danish" },
  { value: "fi", label: "Finnish" },
  { value: "no", label: "Norwegian" },
  { value: "el", label: "Greek" }
]; 