export type CountryLanguageEntry = {
  code: string;
  name: string;
  languages: string[];
};

/**
 * Curated list of key markets supported by MixerAI.
 * Each entry aligns with ISO 3166-1 alpha-2 country codes and
 * provides the primary languages (BCP-47 or ISO 639-1 codes)
 * used for brand configuration.
 */
export const COUNTRY_LANGUAGE_DATA: CountryLanguageEntry[] = [
  { code: 'US', name: 'United States', languages: ['en'] },
  { code: 'CA', name: 'Canada', languages: ['en', 'fr'] },
  { code: 'MX', name: 'Mexico', languages: ['es'] },
  { code: 'BR', name: 'Brazil', languages: ['pt'] },
  { code: 'AR', name: 'Argentina', languages: ['es'] },
  { code: 'CL', name: 'Chile', languages: ['es'] },
  { code: 'CO', name: 'Colombia', languages: ['es'] },
  { code: 'PE', name: 'Peru', languages: ['es'] },
  { code: 'UY', name: 'Uruguay', languages: ['es'] },
  { code: 'PY', name: 'Paraguay', languages: ['es', 'gn'] },
  { code: 'BO', name: 'Bolivia', languages: ['es', 'qu'] },
  { code: 'DO', name: 'Dominican Republic', languages: ['es'] },
  { code: 'CR', name: 'Costa Rica', languages: ['es'] },
  { code: 'PA', name: 'Panama', languages: ['es'] },
  { code: 'GB', name: 'United Kingdom', languages: ['en'] },
  { code: 'IE', name: 'Ireland', languages: ['en', 'ga'] },
  { code: 'FR', name: 'France', languages: ['fr'] },
  { code: 'DE', name: 'Germany', languages: ['de'] },
  { code: 'IT', name: 'Italy', languages: ['it'] },
  { code: 'ES', name: 'Spain', languages: ['es', 'ca', 'eu', 'gl'] },
  { code: 'PT', name: 'Portugal', languages: ['pt'] },
  { code: 'NL', name: 'Netherlands', languages: ['nl'] },
  { code: 'BE', name: 'Belgium', languages: ['nl', 'fr', 'de'] },
  { code: 'SE', name: 'Sweden', languages: ['sv'] },
  { code: 'NO', name: 'Norway', languages: ['nb', 'nn'] },
  { code: 'DK', name: 'Denmark', languages: ['da'] },
  { code: 'FI', name: 'Finland', languages: ['fi', 'sv'] },
  { code: 'AT', name: 'Austria', languages: ['de'] },
  { code: 'CH', name: 'Switzerland', languages: ['de', 'fr', 'it'] },
  { code: 'PL', name: 'Poland', languages: ['pl'] },
  { code: 'CZ', name: 'Czechia', languages: ['cs'] },
  { code: 'SK', name: 'Slovakia', languages: ['sk'] },
  { code: 'HU', name: 'Hungary', languages: ['hu'] },
  { code: 'RO', name: 'Romania', languages: ['ro'] },
  { code: 'BG', name: 'Bulgaria', languages: ['bg'] },
  { code: 'HR', name: 'Croatia', languages: ['hr'] },
  { code: 'SI', name: 'Slovenia', languages: ['sl'] },
  { code: 'GR', name: 'Greece', languages: ['el'] },
  { code: 'TR', name: 'Türkiye', languages: ['tr'] },
  { code: 'UA', name: 'Ukraine', languages: ['uk'] },
  { code: 'RU', name: 'Russia', languages: ['ru'] },
  { code: 'IL', name: 'Israel', languages: ['he', 'ar', 'en'] },
  { code: 'SA', name: 'Saudi Arabia', languages: ['ar'] },
  { code: 'AE', name: 'United Arab Emirates', languages: ['ar', 'en'] },
  { code: 'QA', name: 'Qatar', languages: ['ar', 'en'] },
  { code: 'KW', name: 'Kuwait', languages: ['ar', 'en'] },
  { code: 'ZA', name: 'South Africa', languages: ['en', 'af', 'zu', 'xh'] },
  { code: 'KE', name: 'Kenya', languages: ['en', 'sw'] },
  { code: 'NG', name: 'Nigeria', languages: ['en', 'yo', 'ha', 'ig'] },
  { code: 'EG', name: 'Egypt', languages: ['ar'] },
  { code: 'MA', name: 'Morocco', languages: ['ar', 'fr'] },
  { code: 'GH', name: 'Ghana', languages: ['en', 'ak'] },
  { code: 'ET', name: 'Ethiopia', languages: ['am'] },
  { code: 'AU', name: 'Australia', languages: ['en'] },
  { code: 'NZ', name: 'New Zealand', languages: ['en', 'mi'] },
  { code: 'JP', name: 'Japan', languages: ['ja'] },
  { code: 'KR', name: 'South Korea', languages: ['ko'] },
  { code: 'CN', name: 'China', languages: ['zh-Hans'] },
  { code: 'HK', name: 'Hong Kong SAR', languages: ['zh-Hant', 'en'] },
  { code: 'TW', name: 'Taiwan', languages: ['zh-Hant'] },
  { code: 'SG', name: 'Singapore', languages: ['en', 'zh-Hans', 'ms', 'ta'] },
  { code: 'TH', name: 'Thailand', languages: ['th'] },
  { code: 'VN', name: 'Vietnam', languages: ['vi'] },
  { code: 'MY', name: 'Malaysia', languages: ['ms', 'en', 'zh-Hant', 'ta'] },
  { code: 'ID', name: 'Indonesia', languages: ['id'] },
  { code: 'PH', name: 'Philippines', languages: ['fil', 'en'] },
  { code: 'IN', name: 'India', languages: ['en', 'hi', 'bn', 'ta', 'te', 'mr'] },
  { code: 'PK', name: 'Pakistan', languages: ['ur', 'en'] },
  { code: 'BD', name: 'Bangladesh', languages: ['bn'] },
  { code: 'LK', name: 'Sri Lanka', languages: ['si', 'ta'] },
  { code: 'NP', name: 'Nepal', languages: ['ne'] },
  { code: 'KH', name: 'Cambodia', languages: ['km'] },
  { code: 'LA', name: 'Laos', languages: ['lo'] },
  { code: 'MM', name: 'Myanmar', languages: ['my'] }
];
