-- Bootstrap creation of public.brands if missing (placed before functions migration)

CREATE TABLE IF NOT EXISTS "public"."brands" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "name" "text" NOT NULL,
    "website_url" "text",
    "country" "text",
    "language" "text",
    "brand_identity" "text",
    "tone_of_voice" "text",
    "guardrails" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "brand_color" "text" DEFAULT '#3498db'::"text",
    "brand_summary" "text",
    "brand_admin_id" "uuid",
    "normalized_website_domain" "text",
    "content_vetting_agencies" "text"[],
    "approved_content_types" "jsonb",
    "master_claim_brand_id" "uuid",
    "website_urls" "jsonb" DEFAULT '[]'::"jsonb",
    "logo_url" "text",
    "additional_website_urls" "text"[] DEFAULT ARRAY[]::"text"[],
    CONSTRAINT "check_website_urls_is_array" CHECK (("jsonb_typeof"("website_urls") = 'array'::"text"))
);

DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema = 'public' AND table_name = 'brands'
  ) THEN
    ALTER TABLE ONLY "public"."brands" FORCE ROW LEVEL SECURITY;
  END IF;
END $$;

COMMENT ON COLUMN "public"."brands"."brand_color" IS 'HEX color code for brand visual identity, generated by AI or manually set';
COMMENT ON COLUMN "public"."brands"."brand_summary" IS 'Short summary of the brand for display in listings';
COMMENT ON COLUMN "public"."brands"."brand_admin_id" IS 'Designated admin for handling rejected content in workflows';
COMMENT ON COLUMN "public"."brands"."content_vetting_agencies" IS 'Array of IDs or names of selected content vetting agencies associated with the brand.';
COMMENT ON COLUMN "public"."brands"."approved_content_types" IS 'JSONB array or object storing approved content types for the brand (e.g., array of content type IDs or names).';
