-- Add brand_color column to brands table
ALTER TABLE brands ADD COLUMN IF NOT EXISTS brand_color TEXT DEFAULT '#3498db';

-- Update existing rows with default color
UPDATE brands SET brand_color = '#3498db' WHERE brand_color IS NULL;

-- Comment explaining purpose
COMMENT ON COLUMN brands.brand_color IS 'HEX color code for brand visual identity, generated by AI or manually set'; 