'use client';

import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  ClipboardCheck,
  Copy,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideProps,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Plus,
  Pizza,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  LogOut,
  type Icon as LucideIcon
} from "lucide-react";

export type Icon = typeof LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  laptop: Laptop,
  moon: Moon,
  sun: SunMedium,
  warning: AlertTriangle,
  check: Check,
  file: File,
  fileText: FileText,
  plus: Plus,
  creditCard: CreditCard,
  moreVertical: MoreVertical,
  image: Image,
  twitter: Twitter,
  pizza: Pizza,
  page: File,
  copy: Copy,
  clipboardCheck: ClipboardCheck,
  logOut: LogOut,
}; 